---
ID: "3810ff13-51cc-4dcc-ba12-d3ce74e6b90b"
Parent: "87cbece1-735c-43dd-b904-108d0d2a9ecb"
Template: "87cbece1-735c-43dd-b904-108d0d2a9ecb"
Path: /sitecore/templates/Feature/OrderCloud/Shopping Cart Icon/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{33C4841E-42C6-405D-9CCC-02AFCB6B6ED6}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "93fcdce3-2c8f-49a3-af9d-f519e7cbe2a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\George Haeger
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230814T213852Z
