---
ID: "e5e96109-885c-4f41-915a-3422609ff940"
Parent: "555c2b8e-dd52-472a-a2de-c3e95d84fcbf"
Template: "555c2b8e-dd52-472a-a2de-c3e95d84fcbf"
Path: /sitecore/templates/Feature/OrderCloud/Rendering Parameters/Product Lists/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "12cf0552-daff-4a3d-9301-c646694eda13"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\George Haeger
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230814T201546Z
