---
ID: "da9965a4-4db6-4f5f-ad4a-768aaa529ee2"
Parent: "8a153de9-7d48-4a14-9573-b754ad6da49e"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/Order-Cloud-Buyer-Business/Play-Marketplace/Settings/Shared Sites Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230802T211932Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\George Haeger
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\George Haeger
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d695a1b9-2a63-4ff1-99d2-7cc683dd96d4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\George Haeger
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230802T211932Z
