---
ID: "a6ea861c-c51c-4abe-b48d-17789955c418"
Parent: "35b27e1c-b0ad-4e36-aeb9-91a37358ff0c"
Template: "35b27e1c-b0ad-4e36-aeb9-91a37358ff0c"
Path: /sitecore/templates/Feature/OrderCloud/Rendering Parameters/Product Promo/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d3fa5690-d313-4ddd-ad04-5f9a035290eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\O3rvvRLsLy
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230616T161959Z
