---
ID: "17e308fb-100b-4b65-bcc0-9120d66de7b2"
Parent: "45ee259f-8b77-43f9-af8a-ed02852306ec"
Template: "ec494725-c89d-488c-86fe-252a08b53d01"
Path: "/sitecore/content/Order-Cloud-Buyer-Business/Play-Marketplace/Home/landing-pages/Prod catalog launch"
BranchID: "39ba9999-8032-45d8-848c-a491e5822b5c"
SharedFields:
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{EE3FAB03-3D84-469A-9567-368C5872BF80}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{44E5078B-0171-4995-8186-4E9EC1BF2B92}" />
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{A4C08DF9-7CFC-433B-8A6B-102618F0A70D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "1c2db008-3751-402e-ba49-d2d5e3e18645"
      Hint: Content
      Value: <p>Lorem ipsum dolor sit amet lorem ipsum dolor sit amet</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240222T184149Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Prod catalog launch
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Scott Mulligan
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Scott Mulligan
    - ID: "7640c657-781a-4fef-8afe-7a9fdf65710f"
      Hint: Title
      Value: Example Page Title
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "39044d7c-083b-4402-be7f-b915b0b8df2e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Scott Mulligan
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240222T184151Z
