---
ID: "e5dd8e27-160d-4b8a-a2aa-1bc19ec068e9"
Parent: "32533e2b-0bb0-4d50-a6d7-4ffd0ab4d83f"
Template: "32533e2b-0bb0-4d50-a6d7-4ffd0ab4d83f"
Path: /sitecore/templates/Feature/OrderCloud/Search Input/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{33C4841E-42C6-405D-9CCC-02AFCB6B6ED6}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9aa083b7-1b74-4c20-b50b-2fbcd68a6b8f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\George Haeger
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230814T213116Z
