---
ID: "46a5f9b4-aa4b-4a18-b607-bf55ecb0ef9c"
Parent: "aa130346-7fbe-472c-803b-ed73d97f3002"
Template: "aa130346-7fbe-472c-803b-ed73d97f3002"
Path: /sitecore/templates/Feature/OrderCloud/Rendering Parameters/LocationPicker/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230717T210603Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\O3rvvRLsLy
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\O3rvvRLsLy
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "802d9361-2c6c-474b-92be-bd0a4bcdefb9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\O3rvvRLsLy
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230717T210603Z
